### ISSUE TITLE
Should this repository be archived or should the README be updated?

### ISSUE THREAD

**Issue by raxityo** [segmentio/snippet#101]
If I understand correctly, this repository and approach to load analytics.js have been deprecated in favor of Analytics 2.0.

However, there is no clear indication on this repository and it creates confusion when we land here after googling "Segment snippet" 🙂 
It would be very helpful if this repository had been archived and/or the readme would link to https://github.com/segmentio/analytics-next/ as the new official way of using Segment.

**Comment by silesky** [comment]
Actually, this repo is just a wrapper around a couple functions that return strings --  analytics 2.0 has no effect on this one way or another.

It basically does the same thing as this:
![image](https://user-images.githubusercontent.com/5115498/233512602-1201a71c-ac30-4fb9-964a-461f962d3baa.png)
