### ISSUE TITLE
Tracking events lost when using Intercom integration

### ISSUE THREAD

**Issue by katiefenn** [segmentio/snippet#20]
Hi there.

I've noticed calls to `track` and `identify` getting lost on our site, which uses the Segment Intercom integration. The calls in question are taking place in-between loading of `analytics.min.js` and loading of the Intercom scripts.

I believe this to be because queued events are dequeued when the `analytics.min.js` script finishes loading, but the API queues from the snippet remain in place until integration scripts finish loading. I found some calls still in the queue at the point that the snippet's `ready` callback is run.

Here's an illustration of these events that I am logging out to the JavaScript console to debug them:

<img width="602" alt="screen shot 2016-06-15 at 14 55 33" src="https://cloud.githubusercontent.com/assets/1410204/16083577/61eaf900-330d-11e6-9fbb-d3c39fc3a22e.png">

I've gotten around this by changing the `ready` callback to the following:

```
  analytics.ready(function () {
    // KF: Dequeue events queued while waiting for scripts to load
    // This fixes an issue where events queued after Segment script
    // loads, but before the Intercom script loads, are ignored.
    while (analytics && analytics.length > 0) {
      var args = analytics.shift();
      var method = args.shift();
      if (window.analytics[method]) window.analytics[method].apply(window.analytics, args);
    }

    for (var i = 0; i < methods.length; i++) {
      var key = methods[i];
      analytics[key] = window.analytics[key];
    }
  });
```

Happy to discuss this problem or provide a pull request.

Thanks!

**Comment by tsholmes** [comment]
The `analytics` object that we set up to queue calls until the library loads does not continue to function once the library loads. It looks like you may be holding a reference to that original `analytics` object and making calls to it after the library loads. Instead try calling `window.analytics.track/page/identify` to always reference the proper analytics object.

**Comment by pooyaj** [comment]
second the above answer!
