### ISSUE TITLE
Webpack issue

### ISSUE THREAD

**Issue by joeltello** [segmentio/snippet#21]
hey guys! I'm having some issues integrating the library in my React application...it fails when I try to build my app using webpack...here is my code:

```
import React, { PropTypes, Component } from 'react'
import segmentioSnippet from 'segmentio-snippet'

export default class Analytics extends Component {
  static propTypes = {
    host: PropTypes.string,
    key: PropTypes.string.isRequired,
  }

  static defaultProps = {
    host: 'cdn.segment.com',
  }

  render() {
    const { key, host } = this.props
    // Generate snippet code
    const snippet = segmentioSnippet.min({
      apiKey: key,
      host,
    })
    // Inject code into script tag
    return (
      <script type="text/javascript">{snippet}</script>
    )
  }
}
```

Here's part of the error log:

```
frontend │ WARNING in ./~/handlebars/lib/index.js
frontend │ require.extensions is not supported by webpack. Use a loader instead.
frontend │
frontend │ WARNING in ./~/handlebars/lib/index.js
frontend │ require.extensions is not supported by webpack. Use a loader instead.
frontend │
frontend │ WARNING in ./~/handlebars/lib/index.js
frontend │ require.extensions is not supported by webpack. Use a loader instead.
frontend │
frontend │ ERROR in ./~/segmentio-snippet/lib/index.js
frontend │ Module not found: Error: Cannot resolve module 'fs' in /usr/src/app/node_modules/segmentio-snippet/lib
frontend │  @ ./~/segmentio-snippet/lib/index.js 7:11-24 12:9-22
frontend │
frontend │ ERROR in ./~/handlebars/lib/index.js
frontend │ Module not found: Error: Cannot resolve module 'fs' in /usr/src/app/node_modules/handlebars/lib
frontend │  @ ./~/handlebars/lib/index.js 19:13-26
```

Any help will be very welcome

**Comment by jordanh** [comment]
I was having the same difficulty in [our application](https://github.com/ParabolInc/action). It was really frustrating.

We ended up just using the segment snippet from the CDN. We're using react. We emit a `<script>` tag in the bit of our server code that generates the information for `<head>`:

```javascript
return (
        {process.env.SEGMENT_WRITE_KEY && <script type="text/javascript" async src={segmentCdnSrc} />}
);
```

The `segmentCdnSrc` is set this way:

```javascript
export default (key, proto = 'http', cdn = 'cdn.segment.com') => {
  if (!key) {
    return '';
  }
  proto = process.env.PROTO || proto;
  return `${proto}://${cdn}/analytics.js/v1/${key}/analytics.min.js`;
};
```

It wasn't ideal, but it allowed us to move ahead.

**Comment by jordanh** [comment]
Ah, I almost forgot. I made this version too, which you should be able to use:

https://github.com/jordanh/segmentio-snippet-lite

**Comment by tsholmes** [comment]
Hi @joeltello

We just released a new version of the snippet library that is compatible with webpack and browserify. Note that the package name has changed to `@segment/snippet`, so try installing `@segment/snippet@4.0.0` and let me know if that fixes the issue.

Tom

**Comment by jordanh** [comment]
We just tried the new version. Works great with (our app)[https://github.com/ParabolInc/action]. Thank you for the update!
