### ISSUE TITLE
Convenience method

### ISSUE THREAD

**Issue by jonathansamines** [segmentio/snippet#36]
At work we currently use this module to render (server side) the analytics script in a Node based application. We usually toggle certain features based on configurable runtime flags. On of those flags is if the snippet should be render minified or not. Having a single method which allow for a simple toggle is convenient in this case:

```js
const { include } = require('@segment/snippet');

const snippet = include({
 minified: Boolean,
 ...allOtherPropsAvailable,
});
```

Is that something you would consider adding?

**Comment by pooyaj** [comment]
@jonathansamines would the `snippet.max(` and `snippet.min(` solves this issue?

**Comment by jonathansamines** [comment]
@pooyaj Yes it does, but we usually minify based on the environment information, and therefore we usually implement a little helper on top of those functions (min and max) to decide whether or not to minify the snippet.

**Comment by pooyaj** [comment]
Discussed internally, and closing this, as this is a specialized use-case of snippet in a node-application, and won't be a common use-case for most customers.
