### ISSUE TITLE
always make sure callbacks are called

### ISSUE THREAD

**Issue by ianstormtaylor** [segmentio/snippet#5]
in case analytics.js fails to load (sometimes adblock blocks it) it would be good if the snippet had some logic to make sure callbacks to `track`/`identify` etc always got called even if the script fails to load

**Comment by jschroeter** [comment]
+1

**Comment by stevenmiller888** [comment]
+1. Looks like this is still an issue @ianstormtaylor. Just got another request for it.

**Comment by daniel-sim** [comment]
+1. Hoping the snippet can be drop-in-and-forget rather than cludging something together myself to handle callbacks when analytics.js is blocked

**Comment by afraser** [comment]
+1. u-block kills it and kills all tracked links on our site in the process.
