### ISSUE TITLE
TypeScript Declarations

### ISSUE THREAD

**Issue by employee451** [segmentio/snippet#57]
I would love to see TypeScript declarations for this :-)

**Comment by JackCuthbert** [comment]
Thought I might check up on my PR and found this, I've addressed this issue in https://github.com/segmentio/snippet/pull/55 but it seems there's an issue with the CI tooling and no one has been around to merge/fix it.

While my PR is waiting to be merged, you should be able to drop the contents of [this file](https://github.com/segmentio/snippet/pull/55/files#diff-a150fb53afee945f23f3fe7c176007111f3ba81bb0d188af4077d4a0fc4caa37) into a `.d.ts` file in your TypeScript project and declarations should work :smile:

**Comment by juliofarah** [comment]
Fixed by @JackCuthbert on https://github.com/segmentio/snippet/pull/55 and published no version 4.14.0

**Comment by brettinternet** [comment]
@juliofarah I get an error on that version:

```
Module not found: Can't resolve '../dist/max.template'
```

I don't see the `dist` folder in my `node_modules/@segment/snippet` for version `4.14.0`
