### ISSUE TITLE
Dist not included in 4.14.0

### ISSUE THREAD

**Issue by gundamMC** [segmentio/snippet#67]
Just tested out 4.14.0 and got this error `Error: Cannot find module '../dist/max.template'`. Seems like the `dist/` folder isn't included in the build.

Running `build.js` generates `dist/` and fixes the error.

**Comment by altechzilla** [comment]
Same issue here.

**Comment by altechzilla** [comment]
Any thoughts @juliofarah ? It breaks our automated build processes on every push to staging because we run `npm-check-updates`. Can you run `build.js` and generate the `dist` folder / include it in the master repo?

**Comment by juliofarah** [comment]
Hey! Sorry about that, folks, I'm publishing a patch right now.

**Comment by juliofarah** [comment]
Version 4.14.1 has been published and the templates are in place
![image](https://user-images.githubusercontent.com/484013/124508373-a777cd00-dd84-11eb-92ab-6540bccf3d75.png)
