### ISSUE TITLE
Types failing in `4.14.2`

### ISSUE THREAD

**Issue by fzembow** [segmentio/snippet#69]
Hi!

I updated from `4.13.1` to `4.14.2`, and now when we run `tsc --noEmit`, the following error is displayed

```
./node_modules/@segment/snippet/types.d.ts:12:13 - error TS2411: Property 'All' of type 'boolean | undefined' is not assignable to string index type 'boolean'.

12             All?: boolean
               ~~~
```

We are using typescript `3.8.3` .. a bit dated, but perhaps there is a mistake in this type definition?

**Comment by lizraeli** [comment]
Looks like the error is happening in typescript `4.3.5` too, depending on if strictNullChecks is enabled - [link to playground](https://www.typescriptlang.org/play?ts=4.3.5#code/CYUwxgNghgTiAEBbA9sArhBByAAgZxAHNEQA7AFwHo9SBLAB3pHK3gG8Aoeb+WikGADMoYBAAUohEAHl65WslJ52XHmrBRyRZDACeAfgBc8PORh9Cqtd1JQSRk2YtXr9GMiYx5IPA87WA+ABtAGsQXWNTc1JCAF1Ipxj4AB94UjREACMBFzUAXxcClz4tIREEABlkKGBZeUVlf0CSohhNBSU-XMCAQQgIB0zkZEwoUm6A0PCE6LjjIZGQMYn4AvyOYv4y0Xg6jsaVygAqI-gAFQALBGBkRCg+NLsEAHcruHhyK-gxqAhdeTAeAAdAArZR4MDmOS8ZQXZCmEDAIHwI6UFZw0wOKLOQLwY6nS4IKD0WgAaXCH2Q8Ag1WAvFIHy+NAYTHIyNRK2JZPCWMSllxUDBEk+vNmhxOKxR5y+HnqSkp8HoUDwynIVIABj8-gDgUqpOrkbRBIrJAhaMphBACAAaRlkO2S07qvUgAAUAEp1fANP14M9aL7svBbrRyFokY60biXYNhqMGakJFI9g1xUdHfAAJLGgjkBWWgh2+Dqmk1D1en0QP0BqtBkNhxHIy7mmHwNAEQQYeCCHS8QQZ3TINB+sZ54C6WyIWiV3TexRmEZF0t0tzIUQq4MMz4ISC0MjkAC0eFooG7OgznwsyggtDC8AA4gARMQAJSBkZWy9jizGKXgVRqFMlEKDY1HxXJThfZg0BgeVtyQKAAA8jT3OkADcBGPRRg2NeCtX+adgTBEw6EYZh4EIWgMIZKATHI5B+2sU5ZX2d8mKjHgQEQ+gdDzTtSDAOUEMQ10WIaBwgLwd0ZmcFxwKY+AoPIGC4K+Kc6EEVD4AwmAsIZBii2ZMi2QgjjuC4nivG7NABKE9TRLkfYJMchppMcMUiiAA)

**Comment by lizraeli** [comment]
This error is happening with strict type checks in the following interface:
```typescript

    interface LoadOptions {
        integrations?: {
            All?: boolean
            [key: string]: boolean
        }
    }
```
The problem with the `All` property being optional, is that this allows passing `undefined` as the value, while the indexed type `[key: string]: boolean` defines all properties as being boolean. One option is to simply remove the `All` property from the definition, since it's already included in `[key: string]: boolean`. Another option is to define `integrations` as an intersection type:
```typescript
interface LoadOptions {
    integrations?: {
        All?: boolean
    } & {
        [key: string]: boolean
    }
}
```

**Comment by fzembow** [comment]
Gonna close for now, doesn't seem critical

**Comment by fzembow** [comment]
Whoops, meant to close our internal ticket regarding this. You should definitely still fix :)

**Comment by aslilac** [comment]
It's laughable that you want someone to fix this for free when y'all are paid for a service
