### ISSUE TITLE
Failed to load settings SyntaxError - version `4.15.0`

### ISSUE THREAD

**Issue by AdrienFromToulouse** [segmentio/snippet#77]
Hi!

We are using Nextjs `11.1.2` and since the version `4.15.0` of the snippet we face the following issue:

```
browser.ts:75 Failed to load settings SyntaxError: Unexpected token < in JSON at position 0

[analytics.js] Failed to load Analytics.js SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
```

> Downgrading to `4.13.2` solves it.

The error seems to come from this part of the code:

```js
export function loadLegacySettings(writeKey: string): Promise<LegacySettings> {
  const cdn = window.analytics?._cdn ?? getCDN()
  return fetch(`${cdn}/v1/projects/${writeKey}/settings`)
    .then((res) => res.json())
    .catch((err) => {
      console.warn('Failed to load settings', err)
      throw err
    })
}
```

We saw in the changelog something related to it in https://github.com/segmentio/snippet/pull/73/files

Do we have to upgrade something else on our end to make the `4.15.0` happy?

Cheers!

**Comment by juliofarah** [comment]
Hi, @AdrienFromToulouse 
Thanks for reporting this. We have marked v 4.15 as deprecated on NPM and are currently working on a fix.

**Comment by AdrienFromToulouse** [comment]
`4.15.3` seems to be good now! thanks for your work.

Cheers,

**Comment by juliofarah** [comment]
Thank you once again for raising this issue!
Closing it now as 4.15.3 has a fix!
