### ISSUE TITLE
Will snippet be updated to the v2 source?

### ISSUE THREAD

**Issue by pinindajin** [segmentio/snippet#95]
I was looking through the source to see which version was support and saw the following https://github.com/segmentio/snippet/blob/12e15bcf0a95570dc54e4dfa28f2e28f81a4282b/lib/index.js#L60

Unless the v2 source ends up being available at the v1 path then I assume that there needs to be an update to support the v2 source?

Any word on if there is an intent to do this?

**Comment by silesky** [comment]
It is the v2 source
